packages:
  - packages/*
  - playground
catalog:
  "@ant-design/colors": ^7.2.1
  "@ant-design/fast-color": ^3.0.0
  "@ant-design/icons-vue": ^7.0.1
  "@antfu/eslint-config": ^5.4.1
  "@emotion/hash": ^0.8.0
  "@emotion/unitless": ^0.7.5
  "@testing-library/jest-dom": ^5.16.3
  "@types/jsdom": ^27.0.0
  "@types/node": ^24.7.1
  "@types/stylis": ^4.0.2
  "@types/testing-library__jest-dom": ^5.14.5
  "@v-c/color-picker": ^1.0.0
  "@v-c/resize-observer": ^0.0.2
  "@v-c/util": ^0.0.7
  "@vitejs/plugin-vue": ^6.0.1
  "@vitejs/plugin-vue-jsx": ^5.1.1
  "@vue/test-utils": ^2.4.6
  "@vue/tsconfig": ^0.8.1
  "@vueuse/core": ^13.9.0
  csstype: ^3.1.3
  defu: ^6.1.4
  es-toolkit: ^1.40.0
  eslint: ^9.37.0
  eslint-plugin-format: ^1.0.2
  jiti: ^2.6.1
  jsdom: ^27.0.0
  pinia: ^3.0.3
  stylis: ^4.3.4
  tsdown: ^0.15.6
  typescript: ~5.9.3
  unocss: ^66.5.4
  vite: npm:rolldown-vite@7.1.17
  vite-plugin-inspect: ^11.3.3
  vite-plugin-tsx-resolve-types: ^0.0.4
  vitest: ^3.2.4
  vue: ^3.5.22
  vue-router: ^4.5.1
  vue-tsc: ^3.1.0
