cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - packages/*
  - playground

overrides:
  '@v-c/portal': catalog:vc
  '@v-c/resize-observer': catalog:vc
  '@v-c/trigger': catalog:vc
  '@v-c/util': catalog:vc
  vite: catalog:dev
catalog:
  flexsearch: ^0.8.212

catalogs:
  dev:
    '@antfu/eslint-config': ^7.2.0
    '@changesets/cli': ^2.29.8
    '@testing-library/jest-dom': ^6.9.1
    '@vitejs/plugin-vue': ^6.0.3
    '@vitejs/plugin-vue-jsx': ^5.1.3
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    bumpp: ^10.3.2
    chalk: ^5.6.2
    cli-progress: ^3.12.0
    cross-env: ^10.1.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.1.0
    fs-extra: ^11.3.3
    jiti: ^2.6.1
    jsdom: ^27.3.0
    less: ^4.5.1
    lint-staged: ^16.2.7
    lunar-typescript: ^1.8.6
    mockdate: ^3.0.5
    npm-run-all: ^4.1.5
    picocolors: ^1.1.1
    postcss: ^8.5.6
    postcss-selector-parser: ^7.1.1
    pretty-format: ^30.2.0
    simple-git-hooks: ^2.8.0
    tinyglobby: 0.2.15
    tsdown: ^0.20.1
    tsx: ^4.21.0
    turbo: ^2.7.2
    typedoc: ^0.28.16
    typescript: ~5.9.3
    unocss: ^66.5.10
    vite: ^8.0.0-beta.11
    vite-plugin-dayjs: ^1.0.1
    vite-plugin-inspect: ^11.3.3
    vite-plugin-tsx-resolve-types: ^1.0.1-beta.5
    vitest: ^4.0.17
    vue-tsc: ^3.1.8
  docs:
    '@antdv-next/unocss': ^1.0.0-rc.1
    '@mdit-vue/plugin-frontmatter': 3.0.2
    '@mdit-vue/plugin-headers': ^3.0.2
    '@mdit-vue/plugin-title': ^3.0.2
    '@mdit-vue/plugin-toc': ^3.0.2
    '@mdit-vue/shared': ^3.0.2
    '@mdit-vue/types': ^3.0.2
    '@shikijs/langs': ^3.22.0
    '@shikijs/markdown-it': ^3.20.0
    '@shikijs/themes': ^3.22.0
    '@shikijs/transformers': ^3.20.0
    '@shikijs/twoslash': ^3.20.0
    '@stackblitz/sdk': ^1.11.0
    markdown-it: 14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-async: ^2.2.0
    markdown-it-attrs: ^4.3.1
    markdown-it-container: ^4.0.0
    markdown-it-emoji: ^3.0.0
    markdown-it-ts: 0.0.2
    prismjs: ^1.30.0
    shiki: ^3.20.0
  prod:
    '@ant-design/colors': 7.2.1
    '@ant-design/fast-color': ^3.0.0
    '@antdv-next/happy-work-theme': ^1.0.0-rc.1
    '@antdv-next/icons': ^1.0.0-rc.2
    '@emotion/hash': ^0.8.0
    '@emotion/unitless': ^0.7.5
    '@vueuse/core': catalog:prod
    csstype: ^3.2.3
    dayjs: ^1.11.19
    defu: ^6.1.4
    dom-serializer: ^2.0.0
    domhandler: ^5.0.3
    es-toolkit: 1.43.0
    htmlparser2: ^10.0.0
    lru-cache: ^11.2.4
    mlly: ^1.8.0
    nanoid: ^5.1.6
    pathe: ^2.0.3
    picomatch: ^4.0.3
    pinia: ^3.0.4
    scroll-into-view-if-needed: ^3.1.0
    stylis: ^4.3.6
    throttle-debounce: ^5.0.2
    tslib: ^2.8.1
    vanilla-tilt: ^1.8.1
    vue: ^3.5.27
    vue-router: ^4.6.4
  types:
    '@types/cli-progress': ^3.11.6
    '@types/fs-extra': ^11.0.4
    '@types/jsdom': ^27.0.0
    '@types/markdown-it': 14.1.2
    '@types/markdown-it-attrs': ^4.1.3
    '@types/markdown-it-container': ^2.0.11
    '@types/node': ^25.0.10
    '@types/picomatch': ^4.0.2
    '@types/stylis': ^4.2.7
    '@types/testing-library__jest-dom': ^6.0.0
    '@types/throttle-debounce': ^5.0.2
  vc:
    '@v-c/async-validator': ^1.0.0
    '@v-c/cascader': ^1.0.0
    '@v-c/checkbox': ^1.0.0
    '@v-c/collapse': ^1.0.0
    '@v-c/color-picker': ^1.0.4
    '@v-c/dialog': ^1.0.1
    '@v-c/drawer': ^1.0.0
    '@v-c/dropdown': ^1.0.2
    '@v-c/image': ^1.0.2
    '@v-c/input': ^1.0.2
    '@v-c/input-number': ^1.0.2
    '@v-c/mentions': ^1.0.0
    '@v-c/menu': ^1.0.10
    '@v-c/mutate-observer': ^1.0.1
    '@v-c/notification': ^1.0.0
    '@v-c/pagination': ^1.0.0
    '@v-c/picker': ^1.0.2
    '@v-c/portal': ^1.0.7
    '@v-c/progress': ^1.0.0
    '@v-c/qrcode': ^1.0.0
    '@v-c/rate': ^1.0.0
    '@v-c/resize-observer': ^1.0.8
    '@v-c/segmented': ^1.0.0
    '@v-c/select': ^1.0.9
    '@v-c/slick': ^1.0.0
    '@v-c/slider': ^1.0.10
    '@v-c/steps': ^1.0.0
    '@v-c/switch': ^1.0.0
    '@v-c/table': ^1.0.0
    '@v-c/tabs': ^1.0.1
    '@v-c/textarea': ^1.0.3
    '@v-c/tooltip': ^1.0.2
    '@v-c/tour': ^1.0.3
    '@v-c/tree': ^1.0.2
    '@v-c/tree-select': ^1.0.0
    '@v-c/trigger': ^1.0.10
    '@v-c/upload': ^1.0.0
    '@v-c/util': ^1.0.13
    '@v-c/virtual-list': ^1.0.5

onlyBuiltDependencies:
  - esbuild
  - less
