packages:
  - packages/*
  - playground

catalog:
  '@ant-design/colors': 7.2.1
  '@ant-design/fast-color': ^3.0.0
  '@ant-design/icons-svg': ^4.4.2
  '@antfu/eslint-config': ^5.4.1
  '@changesets/cli': ^2.29.8
  '@emotion/hash': ^0.8.0
  '@emotion/unitless': ^0.7.5
  '@mdit-vue/plugin-frontmatter': 3.0.2
  '@mdit-vue/plugin-headers': ^3.0.2
  '@mdit-vue/plugin-title': ^3.0.2
  '@mdit-vue/plugin-toc': ^3.0.2
  '@mdit-vue/shared': 3.0.2
  '@mdit-vue/types': ^3.0.2
  '@shikijs/markdown-it': ^3.20.0
  '@shikijs/transformers': ^3.20.0
  '@shikijs/twoslash': ^3.20.0
  '@testing-library/jest-dom': ^5.17.0
  '@types/jsdom': ^27.0.0
  '@types/markdown-it': 14.1.2
  '@types/markdown-it-attrs': ^4.1.3
  '@types/markdown-it-container': ^2.0.11
  '@types/node': ^24.10.3
  '@types/picomatch': ^4.0.2
  '@types/stylis': ^4.2.7
  '@types/testing-library__jest-dom': ^5.14.9
  '@v-c/async-validator': ^0.0.1
  '@v-c/cascader': ^0.0.1
  '@v-c/checkbox': ^0.0.2
  '@v-c/collapse': ^0.0.5
  '@v-c/color-picker': ^1.0.3
  '@v-c/dialog': ^0.0.4
  '@v-c/drawer': ^0.0.4
  '@v-c/dropdown': ^1.0.1
  '@v-c/image': ^0.0.3
  '@v-c/input': ^1.0.1
  '@v-c/input-number': ^1.0.0
  '@v-c/mentions': ^0.0.1
  '@v-c/menu': ^1.0.6
  '@v-c/mutate-observer': ^0.0.2
  '@v-c/notification': ^0.0.3
  '@v-c/pagination': ^0.0.1
  '@v-c/picker': ^0.0.7
  '@v-c/progress': ^0.0.2
  '@v-c/qrcode': ^0.0.5
  '@v-c/rate': ^0.0.2
  '@v-c/resize-observer': ^1.0.7
  '@v-c/segmented': ^0.0.8
  '@v-c/select': ^1.0.6
  '@v-c/slick': ^0.0.1
  '@v-c/slider': ^1.0.9
  '@v-c/steps': ^0.0.1
  '@v-c/switch': ^0.0.1
  '@v-c/table': ^0.0.3
  '@v-c/tabs': ^0.0.3
  '@v-c/textarea': ^1.0.1
  '@v-c/tooltip': ^1.0.1
  '@v-c/tour': ^1.0.1
  '@v-c/tree': ^0.0.2
  '@v-c/tree-select': ^0.0.1
  '@v-c/trigger': ^1.0.5
  '@v-c/upload': ^0.0.1
  '@v-c/util': ^1.0.8
  '@v-c/virtual-list': ^1.0.5
  '@vitejs/plugin-vue': ^6.0.3
  '@vitejs/plugin-vue-jsx': ^5.1.2
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': 13.9.0
  bumpp: ^10.3.2
  csstype: ^3.2.3
  dayjs: ^1.11.19
  defu: ^6.1.4
  dom-serializer: ^2.0.0
  domhandler: ^5.0.3
  es-toolkit: 1.43.0
  eslint: ^9.39.2
  eslint-plugin-format: ^1.1.0
  esno: 4.8.0
  htmlparser2: ^10.0.0
  jiti: ^2.6.1
  jsdom: ^27.3.0
  less: ^4.5.1
  lru-cache: ^11.2.4
  markdown-it: 14.1.0
  markdown-it-anchor: ^9.2.0
  markdown-it-async: ^2.2.0
  markdown-it-attrs: ^4.3.1
  markdown-it-container: ^4.0.0
  markdown-it-emoji: ^3.0.0
  markdown-it-ts: 0.0.2
  mlly: ^1.8.0
  nanoid: ^5.1.6
  npm-run-all: ^4.1.5
  pathe: ^2.0.3
  picomatch: ^4.0.3
  pinia: ^3.0.4
  pkg-types: ^2.3.0
  postcss: ^8.5.6
  postcss-selector-parser: ^7.1.1
  scroll-into-view-if-needed: ^3.1.0
  shiki: ^3.20.0
  stylis: ^4.3.6
  tinyglobby: 0.2.15
  tsdown: ^0.15.12
  tslib: ^2.8.1
  turbo: ^2.7.2
  typescript: ~5.9.3
  unocss: ^66.5.10
  vite: ^8.0.0-beta.5
  vite-plugin-dayjs: ^1.0.1
  vite-plugin-inspect: ^11.3.3
  vite-plugin-tsx-resolve-types: ^1.0.1-beta.5
  vitest: ^3.2.4
  vue: ^3.5.25
  vue-router: ^4.6.4
  vue-tsc: ^3.1.8

cleanupUnusedCatalogs: true
