/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        AAffix: typeof import('antdv-next')['Affix'];
        AAlert: typeof import('antdv-next')['Alert'];
        AConfigProvider: typeof import('antdv-next')['ConfigProvider'];
    }
}
