export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('antdv-next')['Affix']
    AButton: typeof import('antdv-next')['Button']
    AAlert: typeof import('antdv-next')['Alert']
    AAnchor: typeof import('antdv-next')['Anchor']
    ASpace: typeof import('antdv-next')['Space']
    ADivider: typeof import('antdv-next')['Divider']
    ASpaceCompact: typeof import('antdv-next')['SpaceCompact']
    AFlex: typeof import('antdv-next')['Flex']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ACol: typeof import('antdv-next')['Col']
    ARow: typeof import('antdv-next')['Row']
    ABadge: typeof import('antdv-next')['Badge']
    ABadgeRibbon: typeof import('antdv-next')['Badge']['Ribbon']
    ATag: typeof import('antdv-next')['Tag']
    ACheckableTag: typeof import('antdv-next')['CheckableTag']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutFooter: typeof import('antdv-next')['LayoutFooter']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AEmpty: typeof import('antdv-next')['Empty']
    AResult: typeof import('antdv-next')['Result']
    ASpin: typeof import('antdv-next')['Spin']
    ASkeleton: typeof import('antdv-next')['Skeleton']
    ASkeletonButton: typeof import('antdv-next')['SkeletonButton']
    ASkeletonAvatar: typeof import('antdv-next')['SkeletonAvatar']
    ASkeletonInput: typeof import('antdv-next')['SkeletonInput']
    ASkeletonImage: typeof import('antdv-next')['SkeletonImage']
    ASkeletonNode: typeof import('antdv-next')['SkeletonNode']
    AStatistic: typeof import('antdv-next')['Statistic']
    AStatisticTimer: typeof import('antdv-next')['StatisticTimer']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ATimeline: typeof import('antdv-next')['Timeline']
    AWatermark: typeof import('antdv-next')['Watermark']
    AQrcode: typeof import('antdv-next')['QRCode']
    ACollapse: typeof import('antdv-next')['Collapse']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ASegmented: typeof import('antdv-next')['Segmented']
    APopover: typeof import('antdv-next')['Popover']
    APopconfirm: typeof import('antdv-next')['Popconfirm']
    AFloatButton: typeof import('antdv-next')['FloatButton']
    AFloatBackTop: typeof import('antdv-next')['BackTop']
    AFloatButtonGroup: typeof import('antdv-next')['FloatButtonGroup']
  }
}
