/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        AAffix: typeof import('antdv-next')['Affix'];
        AButton: typeof import('antdv-next')['Button'];
        AAlert: typeof import('antdv-next')['Alert'];
        ASpace: typeof import('antdv-next')['Space'];
        ADivider: typeof import('antdv-next')['Divider'];
        ASpaceCompact: typeof import('antdv-next')['SpaceCompact'];
        AFlex: typeof import('antdv-next')['Flex'];
        AConfigProvider: typeof import('antdv-next')['ConfigProvider'];
    }
}
